# Opción 1: `source .secrets.env` para cargar las variables de entorno en la terminal
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: development
  labels:
    app: simple-crud
    component: redis
    environment: development
type: Opaque
stringData:
  REDIS_PASSWORD: ${REDIS_PASSWORD}

# Opción 2 (sin envsubst)

# kubectl create secret generic redis-secret \
# --from-literal REDIS_PASSWORD=${REDIS_PASSWORD} \
# --namespace development

# Opción 3 (con envsubst)

# source .secrets.env && \
# envsubst < k8s/development/redis-secrets.yaml | kubectl apply -f - --namespace development
