# Se puede combinar estas dos opciones utilizando export o source.
# Puede que quiz치s `source .secrets.env && ...` no funcione, por lo que,
# quiz치s sea mejor exportar las variables de entorno antes de ejecutar el comando.

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: development
  labels:
    app: simple-crud
    component: redis
    environment: development
type: Opaque
stringData:
  REDIS_PASSWORD: ${REDIS_PASSWORD}

# Opci칩n 1 (sin envsubst)

# kubectl create secret generic redis-secret \
# --from-literal REDIS_PASSWORD=${REDIS_PASSWORD} \
# --namespace development

# Opci칩n 2 (con envsubst)

# envsubst < k8s/development/redis-secrets.yaml | kubectl apply -f - --namespace development
